email: reuben@firo.org
name: Firo
description: Firo is a cryptocurrency that focuses on privacy and fungibility.
keywords: "firo, xfr, zcoin, xzc, cryptocurrency"
baseurl: ""
url: "https://firo.org"

markdown: kramdown

# Kramdown was using smart quotes, which messes up CLI examples
# TODO: smart quotes are actually quite pretty, so this is perhaps better handled via a plugin that reverts them for CLI blocks
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
    input: GFM

exclude: ["README.md"]

plugins:
  - jekyll-paginate
  - jekyll-multiple-languages-plugin

# paginate
paginate: 3
paginate_path: "/blog/page:num/"

# jekyll-multiple-languages-plugin settings:
languages: ["en"]